instagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
app_name='instagram'
urlpatterns=[
    path('',views.index, name='index'),
    path('create/post/',views.new_image, name='new_image'),
    path('profile/',views.profile, name='profile'),
    path('<int:image_id>/comment/',views.comment, name='comment'),
    path('like/',views.likes, name='likes'),
    path('follow/',views.follow, name='follow'),
    path('search/',views.search, name='search'),
    path('<int:user_id>/profile',views.post_user, name='post_user'),
    path('update/',views.update_profile, name='update_profile'),
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

instagram_copycat/urls.py
from django.contrib import admin
from django.urls import include, path
from register import views as register_views
from django_registration.backends.one_step.views import RegistrationView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('instagram.urls', namespace='instagram')),
    path('register/',register_views.register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='registration/logout.html'),name='logout'),
    
    #AN ALTERBATIVVE FOR REGISTRATION FOR REFERENCE
    # path('accounts/register/',
    #     RegistrationView.as_view(success_url='/accounts/login/'),
    #     name='django_registration_register'),
    # path('accounts/', include('django_registration.backends.one_step.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
]

instagram/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.
class Images(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='images/')
    image_name=models.CharField(max_length=30, blank=True)
    image_caption=models.TextField()
    likes=models.ManyToManyField(User,related_name='image_likes', blank=True)
    posted=models.DateTimeField(auto_now_add=True)
    
    def save(self):
        super().save()
        
        img=Image.open(self.image.path)
        
        if img.height>720 and img.width>720:
            size=(720,720)
            img.thumbnail(size)
            img.save(self.image.path)
    
    def save_image(self):
        self.save()
    @classmethod   
    def delete_image(cls,delete_id):
        Images.objects.filter(pk=delete_id).delete()
        
    @classmethod
    def update_caption(cls,image_id,caption):
        Images.objects.filter(pk=image_id).update(image_caption=caption)
        updated=Images.objects.get(pk=image_id)
        return updated
    @classmethod
    def get_comments(cls,image_id):
        image=Images.objects.get(pk=image_id)
        image_comments=image.comments_set.all()
        return image_comments
              
    def __str__(self):
        return self.image_caption
    
class Comments(models.Model):
    image=models.ForeignKey(Images, on_delete=models.CASCADE)
    comment=models.CharField(max_length=500)
    likes=models.ManyToManyField(User,related_name='comment_likes', blank=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.comment
    
class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    picture=models.ImageField(upload_to='profile/',default='default.png')
    bio=models.CharField(max_length=100,blank=True)
    followers=models.ManyToManyField(User,blank=True,related_name='followers')
    following=models.ManyToManyField(User,blank=True,related_name='following')
    
    def __str__(self):
        return self.user.username
    
    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)
        img=Image.open(self.picture.path)
        
        if img.height >300 and img.width>300:
            size=(300,300)
            img.thumbnail(size)
            img.save(self.picture.path)

instagram/forms.py
from .models import Images,Comments,Profile
from django import forms
from django.contrib.auth.models import User

class NewImage(forms.ModelForm):
    class Meta:
        model=Images
        fields=['image_caption','image']
        
class NewComment(forms.ModelForm):
    class Meta:
        model=Comments
        exclude=['image','user','likes']
        
        
class UpdateUser(forms.ModelForm):
    email=forms.EmailField()
    class Meta:
        model=User
        fields=['username','email']
        
class UpdateProfile(forms.ModelForm):
    class Meta:
        model=Profile
        fields=['bio','picture']

instagram/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import NewImage,NewComment,UpdateUser,UpdateProfile
from django.contrib.auth.decorators import login_required
from .models import Profile,Images,Comments
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib import messages
from PIL import Image
import numpy as np

# Create your views here.
@login_required
def index(request):
    # images=Images.objects.order_by('-posted')
    user=User.objects.get(pk=request.user.id)
    users=user.profile.following.all()
    if users:
        for user in users:
            followers_images=user.images_set.order_by('-posted')
        current_user=request.user    
        user_images=current_user.images_set.order_by('-posted')
        
        images=np.concatenate((user_images,followers_images,))

        return render(request,'instagram/index.html',{'images':images})  
    
    else:
        messages.warning(request,f'You currently are not following anybody. Search and follow users to view posts!')
    
    return render(request,'instagram/index.html')    
        

@login_required
def new_image(request):
    current_user=request.user
    if request.method=='POST':
        form=NewImage(request.POST,request.FILES)
        if form.is_valid():
            image=form.save(commit=False)
            image.user=current_user
            image.save()
        return redirect('instagram:index')
    
    else:
        form=NewImage()
        
    return render(request, 'instagram/image.html',{'form':form})

@login_required
def profile(request):
    return render(request,'instagram/profile.html')

@login_required
def update_profile(request):
    if request.method=="POST":
        user_update=UpdateUser(request.POST,instance=request.user)
        profile_update=UpdateProfile(request.POST,request.FILES,instance=request.user.profile)
        if user_update.is_valid() and profile_update.is_valid():
            user_update.save()
            profile_update.save()
            
            messages.success(request,f'Updated Successfully!')
            return redirect('instagram:profile')
        
    else:
        user_update=UpdateUser(instance=request.user)
        profile_update=UpdateProfile(instance=request.user.profile)
    return render(request,'instagram/update.html',{'user_update':user_update,'profile_update':profile_update})


@login_required
def comment(request,image_id):
    image=Images.objects.get(pk=image_id)
    comments=Images.get_comments(image_id)
    is_liked=False
    if image.likes.filter(id=request.user.id):
        is_liked=True
        
    current_user=request.user
    if request.method=='POST':
        form=NewComment(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.image=image
            comment.user=current_user
            comment.save()  
            
    else:
        form=NewComment() 
    return render(request, 'instagram/comment.html',{'image':image,'comments':comments,'is_liked':is_liked, 'form':form})


def likes(request):
    image=get_object_or_404(Images,pk=request.POST.get('image_id'))
    is_liked=False
    if image.likes.filter(id=request.user.id):
        image.likes.remove(request.user)
        is_liked=False
    else:
        image.likes.add(request.user)
        is_liked=True
    return HttpResponseRedirect(reverse('instagram:comment', args=(image.id,)))
#FOLLOW BUTTON
def follow(request):
    current_user=request.user
    user=get_object_or_404(User, pk=request.POST.get('user_id'))
    is_followed=False
    if user.profile.followers.filter(id=request.user.id):
        user.profile.followers.remove(request.user)
        current_user.profile.following.remove(user)
        is_followed=False
    
    else:
        user.profile.followers.add(request.user)
        current_user.profile.following.add(user)
        is_followed=True
    return HttpResponseRedirect(reverse('instagram:post_user', args=(user.id,)))

def search(request):
    if 'search' in request.GET and request.GET['search']:
        search_term=request.GET.get('search')
        searched=User.objects.filter(username=search_term)
        message=f'{search_term}'
        
        return render(request, 'instagram/search.html', {'searches':searched,'message':message})
    
    else:
        message='Search not found!'
        return render(request,'instagram/search',{'message':message})
        
        
#VIEW FOR A PARICULAR IMAGE USER
def post_user(request, user_id):
    user=User.objects.get(pk=user_id)
    #SEARCHES IF THE CURRENT USER IS ALLREADY FOLLOWING THE USER
    is_followed=False
    if user.profile.followers.filter(id=request.user.id):
        is_followed=True
    return render(request,'instagram/image_user.html',{'user':user,'is_followed':is_followed})

templates/instagram/comment.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block styles %}
    {% bootstrap_css %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-2 col-md-2"></div>
        <div class="col-lg-8 col-md-8 mt-2">
            <div class="card m-3" style="width: auto; margin-left: 10px;">
                <div>
                    <img class="m-2 rounded-circle" src="{{image.user.profile.picture.url}}" alt="" style="height: 40px; width: 40px;"><a href="{% url 'instagram:profile'%}" style="text-decoration: none;">{{image.user.username}}</a><span></span><span class="small ml-2">{{image.posted |  date:"M d,Y,f A"}}</span>
                </div>
                <a href=""><img src="{{image.image.url}}" class="card-img-top img-responsive index_image" id="image" alt="IMAGE" title="" style="height:70vh; width: 100%;" ></a>
                <div class="card-body">
                    <div class="form-inline">
                        <p style="font-size: 1.8em;"> <button class="border mt-3"><a href="{% url 'instagram:comment' image.pk %}" style="text-decoration: none; color: black;"><i class="far fa-comment"></i></a> </button>
                            <form action="{% url 'instagram:likes' %}" method="POST" class="ml-3 mt-0">
                                {% csrf_token%}
                                {% if is_liked%}
                                <button type="submit" name="image_id" value="{{image.id}}" class="border bg-danger" style="font-size: 1.8em;"><a style="text-decoration: none;"> <i class="far fa-heart"></i></a></button>
                                {% else%}
                                <button type="submit" name="image_id" value="{{image.id}}" class="border" style="font-size: 1.8em;"><a style="text-decoration: none; color: black;" > <i class="far fa-heart"></i></a></button>
                                {% endif %}
                            </form> 
                        </p>
                    </div>
                    <p class="" style="font-weight:bolder ;">{{image.likes.count}} <span class="ml-1">likes</span></p>
                    <p class="card-text" style="font-size: 0.9em;"><a href="{% url 'instagram:post_user' image.user.id%}" class="mr-1" style="font-weight: bolder ; text-decoration: none;">{{image.user.username}}</a>{{image.image_caption}}</p>

                    <form  action="{%url 'instagram:comment' image.pk%}" method="post" enctype="multipart/form-data">
                        {%csrf_token%}
                    
                        {% bootstrap_form form%}
                        <input type="submit" class="btn btn-success btn-sm" value="Comment">
                      </form>
                </div>  <hr>
                <h4 class="ml-3" style="font-weight: bold;"> View all comments </h4> 
                <ul style="list-style-type: none;">
                    {% for comment in comments%}
                    <li class="row">
                        <div class="col-md-2 col-lg-2 ">
                            <img src="{{comment.user.profile.picture.url}}" alt="IMAGE" style="height: 40px; width: 40px;" class="rounded-circle">
                        </div>
                        <div class="col-md-8 col-lg-8" style="font-size: 0.9em;">
                            <a href="{% url 'instagram:profile'%}" class="mr-1" style="font-weight: bolder ; text-decoration: none;">{{comment.user.username}}</a><br>
                            <span class="rounded" >{{comment.comment}} </span>                        
                        </div>
                        <div class="col-md-2 col-lg-2"></div>
                    </li><hr><br>
                    {% endfor%}
                </ul>         
            </div>               
        </div>
        <div class="col-lg-2 col-md-2"></div>
    </div>
</div>
{% endblock %}

templates/instagram/image.html
{% extends 'base.html'%}
{% load bootstrap4 %} 
{% load static %}
{% block content%}
<div class="container mt-3">
    <div class="col-lg-2 col-md-2 col-xs-0"></div>
    <div class="col-lg-8 col-md-8">
        <form  action="{%url 'instagram:new_image'%}" method="post" enctype="multipart/form-data">
            {%csrf_token%}

            {% bootstrap_form form%}
            <input type="submit" class="btn btn-success btn-lg" value="Post">
        </form>
    </div>
    <div class="col-lg-2 col-md-2 col-xs-0"></div>
</div>
{% endblock%}

templates/instagram/image_user.html
{% extends 'base.html'%}
{% load bootstrap4 %} 
{% load static %}
{% block title%}
{{user.username}}
{% endblock%}
{% block content%}
<div class="container-fluid">
<div class="row mt-4">
    <div class="col-md-2 col-lg-2"></div>
    <div class="col-md-8 col-lg-8 col-sm-10">
        <div class="card  mb-3" style="width: 100%;">
            <div class="container-fluid" >
                <div class="row mb-2">
                    <div class="col-lg-4 col-md-4 col-xs-12 ml-2 mt-2 ">
                        <img src="{{user.profile.picture.url}}" class="img-circle rounded-circle image-fluid" alt="..." style="width: 220px; height: 220px;">
                    </div>
                
                    <div class="col-lg-6 col-md-6 col-xs-12">
                        <h2 class="card-title">{{user.username}}</h2>
                        <p class="card-text">Email Adress: {{user.email}}</p> 
                        <div class="form-inline ">
                        <p>Followers <span class="badge badge-dark mr-3">{{user.profile.followers.count}}</span></p>
                        <p>Following <span class="badge badge-secondary">{{user.profile.following.count}}</span></p>
                        </div>
                        {% if user.profile.bio%}
                        <p class="card-text">About Me: {{user.profile.bio}}</p>
                        {%endif%}

                        {% if user.id is request.user.id%}
                        <a href="{% url 'instagram:update_profile' %}" class="btn btn-success btn-sm"><small>Update Settings</small></a>
                        {% endif%}
                        <!-- Follow and Followers -->
                        <div>
                            <form action="{% url 'instagram:follow'%}" method="POST">
                                {% csrf_token%}
                                {%  if is_followed%}
                                    <button type="submit" name='user_id' value="{{user.pk}}" class="btn btn-danger btn-sm">Following</button>
                                {% else %}
                                    <button type="submit" name='user_id' value="{{user.pk}}" class="btn btn-primary btn-sm">Follow</button>
                                {% endif %}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-2 col-lg-2"></div>
</div>
</div>
<div class="row">
    <div class="col-lg-12 col-md-12" >
        <div class="row">
            {%for image in user.images_set.all%}
            <div class="col-lg-4 col-md-4 mb-2" style="padding-right: 10px;">
                <div class="card" style="width: 100%; margin-left: 10px;">
                    <a href="{% url 'instagram:comment' image.pk %}"><img src="{{image.image.url}}" class="card-img-top img-responsive index_image" id="image" alt="IMAGE" title="" style="height:70vh; width: 100%;" ></a>
                    <div class="card-body">
                        <p style="font-size: 1.8em;"> <a href="{% url 'instagram:comment' image.pk %}" style="text-decoration: none; color: black;"><i class="far fa-comment"></i> </a style="text-decoration: none; color: black;"> <i class="far fa-heart"></i></p>
                        <p class="" style="font-weight:bolder ;">{{image.likes.count}} <span class="ml-1">likes</span></p>
                        <p class="card-text" style="font-size: 0.9em;"><a href="{% url 'instagram:post_user' image.user.id%}" class="mr-1" style="font-weight: bolder ; text-decoration: none;">{{image.user.username}}</a>{{image.image_caption}}</p>

                    </div>  
                </div>               
            </div>
            {%endfor%}
        </div>
    </div>
</div>
{% endblock%}

templates/instagram/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block styles %}
    {% bootstrap_css %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        {%for image in images%}
        <div class="col-lg-2 col-md-2"></div>
        <div class="col-lg-8 col-md-8 mt-2">
            <div class="card m-3" style="width: auto; margin-left: 10px;">
                <div>
                    <img class="m-2 rounded-circle" src="{{image.user.profile.picture.url}}" alt="" style="height: 40px; width: 40px;"><a href="{% url 'instagram:post_user' image.user.id %}" style="text-decoration: none;">{{image.user.username}}</a> <span></span><span class="small">{{image.posted |  date:"M d,Y,f A"}}</span>
                </div>
                <a href="{% url 'instagram:comment' image.pk %}"><img src="{{image.image.url}}" class="card-img-top img-responsive index_image" id="image" alt="IMAGE" title="" style="height:70vh; width: 100%;" ></a>
                <div class="card-body">
                    <p style="font-size: 1.8em;"> <a href="{% url 'instagram:comment' image.pk %}" style="text-decoration: none; color: black;"><i class="far fa-comment"></i> </a style="text-decoration: none; color: black;"> <i class="far fa-heart"></i>
                    </p>
                    <p class="" style="font-weight:bolder ;">{{image.likes.count}} <span class="ml-1">likes</span></p>
                    <p class="card-text" style="font-size: 0.9em;"><a href="{% url 'instagram:post_user' image.user.id %}" class="mr-1" style="font-weight: bolder ; text-decoration: none;">{{image.user.username}}</a>{{image.image_caption}}</p>
                </div>
                
            </div>               
        </div>
        <div class="col-lg-2 col-md-2"></div>
        {%endfor%}
    </div>
</div>
{% endblock %}

templates/instagram/profile.html
{% extends 'base.html'%}
{% load bootstrap4 %} 
{% load static %}
{% block title%}
{{user.username}}
{% endblock%}
{% block content%}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2 col-lg-2"></div>
        <div class="col-md-8 col-lg-8 col-sm-10">
            <div class="card  mt-3">
                <!-- new conatiner -->
                <div class="container-fluid" >
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-xs-12 ml-2 mt-2 ">
                            <img src="{{user.profile.picture.url}}" class="img-circle rounded-circle image-fluid" alt="..." style="width: 220px; height: 220px;">
                        </div>
                    
                        <div class="col-lg-6 col-md-6 col-xs-12">
                            <h2 class="card-title">{{user.username}}</h2>
                            <p class="card-text">Email Adress: {{user.email}}</p>
                            {% if profile.bio%}
                            <p class="card-text">About Me: {{user.profile.bio}}</p>
                            {%endif%} 
        
                            <p>Followers <span class="badge badge-dark">{{user.profile.followers.count}}</span></p>
                            <p>Following <span class="badge badge-secondary">{{user.profile.following.count}}</span></p>
                
                            <a href="{% url 'instagram:update_profile' %}" class="btn btn-success btn-sm"><small>Update Settings</small></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2 col-lg-2"></div>
    </div>

    <div class="row mt-3">
        <div class="col-lg-12 col-md-12" >
            <div class="row">
                {%for image in user.images_set.all%}
                <div class="col-lg-4 col-md-4 mb-2" style="padding-right: 10px;">
                    <div class="card" style="margin-left: 0px;">
                        <a href="{% url 'instagram:comment' image.pk %}"><img src="{{image.image.url}}" class="card-img-top img-responsive index_image" id="image" alt="IMAGE" title="" style="height:50vh; width: 100%;" ></a>
                        <div class="card-body">
                            <div class="form-inline">
                                <p style="font-size: 1.8em;"> <button class="border mt-3"><a href="{% url 'instagram:comment' image.pk %}" style="text-decoration: none; color: black;"><i class="far fa-comment"></i></a> </button>
                                    <form action="{% url 'instagram:likes' %}" method="POST" class="ml-3 mt-0">
                                        {% csrf_token%}
                                        {% if is_liked%}
                                        <button type="submit" name="image_id" value="{{image.id}}" class="border bg-danger" style="font-size: 1.8em;"><a style="text-decoration: none;"> <i class="far fa-heart"></i></a></button>
                                        {% else%}
                                        <button type="submit" name="image_id" value="{{image.id}}" class="border" style="font-size: 1.8em;"><a style="text-decoration: none; color: black;" > <i class="far fa-heart"></i></a></button>
                                        {% endif %}
                                    </form> 
                                </p>
                            </div>
                            <p class="" style="font-weight:bolder ;">{{image.likes.count}} <span class="ml-1">likes</span></p>
                            <p class="card-text" style="font-size: 0.9em;"><a href="{% url 'instagram:profile'%}" class="mr-1" style="font-weight: bolder ; text-decoration: none;">{{image.user.username}}</a>{{image.image_caption}}</p>

                        </div>  
                    </div>               
                </div>
                {%endfor%}
            </div>
        </div>
    </div>
</div>
{% endblock%}

templates/instagram/search.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static%}
{% block styles %}
    {% bootstrap_css %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-3 col-md-3 col-sm-0 col-xs-0"></div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            {% if searches%}
            <h4 class="mt-3">Found {{ searches|length }} of searched term {{message}}</h4>
            <ul style="list-style-type: none;" class="ml-3">
                {% for user in searches%}
                <li>
                    <img class="m-2 rounded-circle" src="{{user.profile.picture.url}}" alt="" style="height: 40px; width: 40px;"><a href="{% url 'instagram:post_user' user.id %}" style="text-decoration: none;">{{user.username}}</a>
                </li>
                {% endfor %}
            </ul>
            
            {% else %}
            <h2> Found 0 articles for the search term {{message}}</h2>
            {% endif %}
        </div>
        <div class="col-lg-3 col-md-3 col-sm-0 col-xs-0"></div>
    </div>
</div>
{% endblock %}

templates/instagram/update.html
{%extends "base.html"%}
{% load bootstrap4%}
{% load crispy_forms_tags%}
{% block content %}
<div class="container">
  <div class="row">
    <!-- Empty div -->
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <div class="panel panel-default">

        <div class="panel-heading">
          <h3 class="text-center">Update Profile</h3>
        </div>
        <div class="panel-body">

          <form  action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form user_update%}
            {% bootstrap_form profile_update%}
            <div class="form-group">
              <input type="submit" class="btn btn-primary btn-sm" value="Update">
            </div>

            <input type="hidden" name="next" value="{{next}}">

          </form>

        </div>

      </div>

    </div>
    <!-- empty div -->
    <div class="col-md-3"></div>
  </div>
</div>

{% endblock %}