instagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
app_name='instagram'
urlpatterns=[
    path('',views.index, name='index'),
    path('create/post/',views.new_image, name='new_image'),
    path('profile/',views.profile, name='profile'),
    path('<int:image_id>/comment/',views.comment, name='comment'),
    path('like/',views.likes, name='likes'),
    path('follow/',views.follow, name='follow'),
    path('search/',views.search, name='search'),
    path('<int:user_id>/profile',views.post_user, name='post_user'),
    path('update/',views.update_profile, name='update_profile'),
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

instagram_copycat/urls.py
from django.contrib import admin
from django.urls import include, path
from register import views as register_views
from django_registration.backends.one_step.views import RegistrationView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('instagram.urls', namespace='instagram')),
    path('register/',register_views.register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='registration/logout.html'),name='logout'),
    
    #AN ALTERBATIVVE FOR REGISTRATION FOR REFERENCE
    # path('accounts/register/',
    #     RegistrationView.as_view(success_url='/accounts/login/'),
    #     name='django_registration_register'),
    # path('accounts/', include('django_registration.backends.one_step.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
]

templates/base.html
{% load bootstrap4%}
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title%}
    <title>InstaPost | {{title}}</title>
    {% else %}
    <title>InstaPost</title>
    {% endif%}
    {% block styles %}
        {% bootstrap_css %}
        <link rel="stylesheet" href="{%static 'css/index.css'%}"  >
        <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Tangerine'>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-inverse navbar-dark bg-dark">
        <div class="container-fluid">
          <div class="navbar-header text-center">
            <a class="navbar-brand" id='name' href="{% url 'instagram:index'%}">InstaPost</a>
          </div>
          <div class="float-right">
              <ul style="list-style-type: none;" class="form-inline mt-1">
            {% if user.is_authenticated%}
                <li class="navbar-form"><form action="{% url 'instagram:search' %}">
                    <input type="text" class="" placeholder="Search ....." name="search">         
                    <button class="btn btn-primary btn-sm " type="submit"><i class="fas fa-search"></i></button>
                </form></li>
                <li><a href="{% url 'instagram:new_image' %}" class="nav-item nav-link">Create Post</a></li>
                <li><a href="{% url 'instagram:profile'%}" class="nav-item nav-link">{{user.username}}</a></li>
                <li><a href="{% url 'logout' %}" class="nav-item nav-link">Logout</a></li>
            {% else %}
                <li><a href="{% url 'login' %}" class="nav-item nav-link">Login</a></li>
                <li><a href="{% url 'register' %}" class="nav-item nav-link">Register</a></li>
            {% endif%}
            </ul>
          </div>
    </nav>
    <div class="text-center">
        {% if messages %}
            {% for message in messages%}
                <div class="alert alert-{{message.tags}}">{{message}}</div>
            {% endfor%}
        {% endif %}
    </div>
    {% block content%}
    {% endblock %}
    {% block scripts %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% bootstrap_javascript%}
    {% endblock %}
</body>
</html>